# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Setup a job that uses Nix
description: A set of steps to setup a Github Actions job with Nix
inputs:
  ssh_key:
    description: Optional ssh key. If passed, ssh-agent will be setup in the job
    required: false
  nix_version:
    description: The version of Nix to install. Defaults to the latest stable version.
    required: false
    default: ""

runs:
  using: composite
  steps:
    # https://stackoverflow.com/a/70249520/5408933
    # https://github.com/orgs/community/discussions/26726
    - name: Check if ssh_key available
      id: ssh-key-check
      shell: bash
      run: |
        if [ "${{ inputs.ssh_key }}" != '' ]; then
          echo "available=true" >> $GITHUB_OUTPUT;
        else
          echo "available=false" >> $GITHUB_OUTPUT;
        fi

    - name: Setup SSH agent
      if: ${{ steps.ssh-key-check.outputs.available == 'true' }}
      uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
      with:
        ssh-private-key: ${{ inputs.ssh_key }}

    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        submodules: recursive

    - name: Install Nix (specific version)
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      if: ${{ inputs.nix_version != '' }}
      with:
        nix_version: ${{ inputs.nix_version }}
        nix_conf: |
          system-features = nixos-test benchmark big-parallel uid-range kvm
    
    - name: Install Nix (latest stable)
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      if: ${{ inputs.nix_version == '' }}
      with:
        nix_conf: |
          system-features = nixos-test benchmark big-parallel uid-range kvm
