name: Nix Flake Check
on:
  workflow_call:
    inputs:
      timeout_minutes:
        required: false
        type: number
        default: 10
      nix_version:
        required: false
        type: string
        default: ""
      app_client_id:
        description: The Github App ClientID to authenticate with. If provided, it will
          be used to generate a token for git authentication. If not provided,
          it will fall back to using the `git_https_token` secret for
          authentication.
        required: false
        type: string
        default: ""
    secrets:
      git_https_token:
        required: false
        description: Github Access Token to rewrite git URLs to use HTTPS with
          authentication. If not provided, it will rewrite to standard HTTPS
          URLs without authentication.
      app_private_key:
        description: The private key of the Github App, in PEM format. If provided, it
          will be used to generate a token for git authentication. If not
          provided, it will fall back to using the `git_https_token` secret for
          authentication.
        required: false

jobs:
  nix-flake-check:
    timeout-minutes: ${{ inputs.timeout_minutes }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Github App info
        if: ${{ inputs.app_client_id != '' }}
        id: app-auth
        uses: pedorich-n/github-workflows/.github/actions/app-token@rework-flows # main
        with:
          client_id: ${{ inputs.app_client_id }}
          private_key: ${{ secrets.app_private_key }}

      - name: Setup Nix
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@rework-flows # main
        with:
          nix_version: ${{ inputs.nix_version }}
          git_https_token: ${{ steps.app-auth.outputs.token || secrets.git_https_token }}

      - name: Nix Flake Check
        uses: pedorich-n/github-workflows/.github/actions/nix-flake-check@rework-flows # main
