name: Nix Flake Check
on:
  workflow_call:
    inputs:
      timeout_minutes:
        required: false
        type: number
        default: 10
      nix_version:
        required: false
        type: string
        default: ""
      app_client_id:
        description: The Github App ClientID to authenticate with. If provided, it will
          be used to generate a token for git authentication.
        required: false
        type: string
        default: ""
      app_owner:
        description: If provided, the token will be issued for all repositories in the
          owner (user or organization). If not provided, the token will be
          issued for the repository of the workflow that calls this action.
        required: false
        type: string
        default: ""
      app_repositories:
        description: Comma or newline-separated list of repositories to grant the token
          access to (defaults to current repository if owner is unset)
        required: false
        type: string
        default: ""
    secrets:
      app_private_key:
        description: The private key of the Github App, in PEM format. If provided, it
          will be used to generate a token for git authentication.
        required: false

jobs:
  nix-flake-check:
    timeout-minutes: ${{ inputs.timeout_minutes }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Github App info
        if: ${{ inputs.app_client_id != '' }}
        id: app_auth
        uses: pedorich-n/github-workflows/.github/actions/app-token@394fb5dff4f8ee88f7fec2c55bb178875af055c5 # main
        with:
          client_id: ${{ inputs.app_client_id }}
          private_key: ${{ secrets.app_private_key }}
          owner: ${{ inputs.app_owner }}
          repositories: ${{ inputs.app_repositories }}

      - name: Setup Nix
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@394fb5dff4f8ee88f7fec2c55bb178875af055c5 # main
        with:
          nix_version: ${{ inputs.nix_version }}
          git_https_token: ${{ steps.app_auth.outputs.token }}

      - name: Nix Flake Check
        uses: pedorich-n/github-workflows/.github/actions/nix-flake-check@394fb5dff4f8ee88f7fec2c55bb178875af055c5 # main
