name: Nix Flake Check
on:
  workflow_call:
    inputs:
      timeout-minutes:
        required: false
        type: number
        default: 10
    secrets:
      ssh_key:
        required: false

jobs:
  nix-flake-check:
    timeout-minutes: ${{ inputs.timeout-minutes }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@main
        with:
          ssh_key: ${{ secrets.ssh_key }}
      - name: Flake Check
        run: nix flake check
